### ISSUE TITLE
doesnt build with css on Windows

### ISSUE THREAD

**Issue by fountainpen** [lkhrs/astro-simple#113]
I'mm on windows. Installed astro template, run pnpm bulid, and it doesnt build with CSS at all. 
Can you check into that?

**Comment by fountainpen** [comment]
yeah i ran pnpm install

ok. I'll  try with npm instead.

**Comment by lkhrs** [comment]
Builds with CSS on Windows 11 for me with Nodejs v21.1.0, `npm` 10.2.1 **and** `pnpm` 8.9.2.

`pnpm` uses symlinks to link the packages to project folders, which is how it saves space. I'd check and make sure Developer Mode is turned on in Windows, seems to enable symlink creation.

**Comment by fountainpen** [comment]
ok. maybe i have outdated stuff. running nodejs v20 on windows10
